### ISSUE TITLE
There is an error when the peer.py is executed from the console

### ISSUE THREAD

**Issue by josejuansanchez** [P2PSP/p2psp#26]
```
 File "/p2psp/src/core/peer_ims.py", line 339, in buffer_data
    buffering_adapter.update_widget(BUFFER_STATUS)
NameError: global name 'buffering_adapter' is not defined
```
The problem is in a method that only should be used in the desktop app.
We should try to find a solution to run the peer in console and GUI mode.

**Comment by josejuansanchez** [comment]
Instead to use a binding between the peer (model) and the view we could try to find another solution like the use of the **Observer pattern**.  

@maniotrix What do you think about it?

**Comment by cristobalmedinalopez** [comment]
Perhaps it's possible to avoid modifying peer_ims.py by using inheritance in the same way which it's used here (for example): https://github.com/P2PSP/p2psp/blob/master/src/peer_dbs.py and https://github.com/P2PSP/p2psp/blob/master/src/peer_fns.py

**Comment by maniotrix** [comment]
This error occurs due to execution of main function from peer.py script.It cant find adapter package because of peer.py being the top-level script.

One  solution would be to place this code in a try-except block, but its not good to run unuseful code block every time the function executes.

Another good solution may be   creating a global variable to check if the peer is running in console mode. The code block to update widget will  be run only when that variable is false.

I thought about using observer pattern  as I have used  it before. I did not do this to avoid Peer_IMS from any type of other inheritance besides those in P2PSP Project. Therefore Peer_IMS objects are exactly the same as before. Also using adapter required less changes in core source code .

**Comment by maniotrix** [comment]
I also think that buffering status must be updated from the buffer_data function because of its dynamic nature.

**Comment by josejuansanchez** [comment]
Ok! If the observer pattern is not viable, I think that we should try to find a clean solution (with the minimal possible changes) to allow to run the peer in both modes (console and gui).

**Comment by cristobalmedinalopez** [comment]
Yes, I agree.

**Comment by maniotrix** [comment]
Ok. Global variable will be used to resolve this issue.

**Comment by josejuansanchez** [comment]
@maniotrix @cristobalmedinalopez I have been thinking about a different solution to avoid the use of the adapter in the model. I think that the use of an **EventBus** could do a lot easier the communication between components, avoding the coupling between the view and the model.

I have found the **geeteventbus library** [1] for Python that seems to solve this issue allowing a publish-subscribe-style communication. I don't know if there are better libraries in Python to tackle this issue. May be interesting to perform some test about it. What do you think?

[1] https://pypi.python.org/pypi/geeteventbus/
